[package]
name = "stas"
version = "0.1.0"
authors = ["Petr Machata <pmachata@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
libc = "*"
