[package]
name = "stas"
version = "0.1.0"
authors = ["Petr Machata <pmachata@gmail.com>"]
edition = "2018"

[lib]
name = "stas"
path = "src/lib.rs"

[dependencies]
nix = "*"
neli = { git = "https://github.com/jbaublitz/neli.git" }
libc = "*"
glob = "*"
termion = "1"
fixed = "0.5.*"
